module.exports = {
  testUrl: "https://www.skinnytaste.com/chicken-and-asparagus-lemon-stir-fry/",
  invalidUrl:
    "https://www.skinnytaste.com/chicken-and-asparagus-lemon-stir-fry/notarealurl",
  invalidDomainUrl: "www.invalid.com",
  nonRecipeUrl: "https://www.skinnytaste.com/",
  expectedRecipe: {
    name: "Chicken and Asparagus Lemon Stir Fry",
    ingredients: [
      "1 1/2 pounds skinless chicken breast (cut into 1-inch cubes)",
      "Kosher salt (to taste)",
      "1/2 cup reduced-sodium chicken broth",
      "2 tablespoons reduced-sodium shoyu or soy sauce (Coconut aminos for GF, W30)",
      "2 teaspoons cornstarch (arrowroot powder or tapioca starch for whole30)",
      "2 tablespoons water",
      "1 tbsp canola or grapeseed oil (divided)",
      "1  bunch asparagus (ends trimmed, cut into 2-inch pieces)",
      "6 cloves garlic (chopped)",
      "1 tbsp fresh ginger",
      "3 tablespoons fresh lemon juice",
      "fresh black pepper (to taste)",
    ],
    instructions: [
      "Lightly season the chicken with salt.",
      "In a small bowl, combine chicken broth and soy sauce.",
      "In a second small bowl combine the cornstarch and water and mix well to combine.",
      "Heat a large non-stick wok over medium-high heat, when hot add 1 teaspoon of the oil, then add the asparagus and cook until tender-crisp, about 3 to 4 minutes.",
      "Add the garlic and ginger and cook until golden, about 1 minute. Set aside.",
      "Increase the heat to high, then add 1 teaspoon of oil and half of the chicken and cook until browned and cooked through, about 4 minutes on each side.",
      "Remove and set aside and repeat with the remaining oil and chicken. Set aside.",
      "Add the soy sauce mixture; bring to a boil and cook about 1-1/2 minutes.",
      "Add lemon juice and cornstarch mixture and stir well, when it simmers return the chicken and asparagus to the wok and mix well, remove from heat and serve.",
    ],
    time: {
      prep: "PT5M",
      cook: "PT25M",
      active: "",
      inactive: "",
      ready: "",
      total: "",
    },
    servings: "4 servings",
    image:
      "https://www.skinnytaste.com/wp-content/uploads/2014/03/Chicken-and-Asparagus-Lemon-Stir-Fry-5.jpg",
    aggregateRating: {
      ratingValue: "4.65",
      ratingCount: "65",
    },
    recipeCuisine: ["Chinese", "Japanese"],
  },
};
